import {
    LayoutDashboard,
    CalendarDays,
    CalendarCheck,
    Users,
    Briefcase,
    Clock,
    Contact,
    BarChart3,
    Settings,
    DollarSign,
    Plug,
    ClipboardList,
    Package,
    Users2,
} from "lucide-react";

export const navItems = [
    { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
    { href: "/dashboard/agenda", label: "Agenda", icon: CalendarDays },
    { href: "/dashboard/turnos", label: "Turnos", icon: CalendarCheck },
    { href: "/dashboard/profesionales", label: "Profesionales", icon: Users },
    { href: "/dashboard/servicios", label: "Servicios", icon: Briefcase },
    { href: "/dashboard/horarios", label: "Horarios", icon: Clock },
    { href: "/dashboard/clientes", label: "Clientes", icon: Contact },
    { href: "/dashboard/formularios", label: "Formularios", icon: ClipboardList },
    { href: "/dashboard/paquetes", label: "Paquetes", icon: Package },
    { href: "/dashboard/lista-espera", label: "Lista de espera", icon: Clock },
    { href: "/dashboard/clases-grupales", label: "Clases grupales", icon: Users2 },
    { href: "/dashboard/cobros", label: "Cobros", icon: DollarSign },
    { href: "/dashboard/integraciones", label: "Integraciones", icon: Plug },
    { href: "/dashboard/reportes", label: "Reportes", icon: BarChart3 },
    { href: "/dashboard/configuracion", label: "Configuracion", icon: Settings },
];
