FROM node:22-alpine
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /usr/src/app
COPY package*.json pnpm-lock.yaml* ./
RUN pnpm install || npm install
COPY . .
EXPOSE 80
CMD ["pnpm", "dev", "--port", "80"]
